// <auto-generated />
namespace QuickDefine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adding_columns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_columns));
        
        string IMigrationMetadata.Id
        {
            get { return "201511020131430_adding_columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
